### ISSUE TITLE
getDate error

### ISSUE THREAD

**Issue by Rollietjes** [FreddyFY/material-datepicker#13]
Hi,

Since last week I got an error when the page is loading. It says: Uncaught TypeError: i.getDate is not a function. I didn't change a thing in the code. How can this be fixed?

Is used Method 2 on using this material datepicker.

**Comment by FreddyFY** [comment]
Hi @Rollietjes , thanks for reporting this bug.
Now it should work again.

**Comment by MIJmker** [comment]
Hi @FreddyFY,

Sadly it still doesn't work. We're loading in the following JavaScript:
**https://cdn.rawgit.com/FreddyFY/material-datepicker/master/dist/material-datepicker-with-moment-js.min.js**

Perhaps it could be a server cache thing, since I see you're git repo should be correct. Sadly it's not client side cache since I couldn't get it to refresh locally.

Is there any chance you can do something about it?

**Comment by FreddyFY** [comment]
You can use this link. It will work with it:
https://cdn.rawgit.com/FreddyFY/material-datepicker/1.0.5/dist/material-datepicker-with-moment-js.min.js

It's better to download the files, instead of using the rawgit cdn server.

I've also updated the [Readme.md](https://github.com/FreddyFY/material-datepicker/blob/master/README.md), with this information. 56e2565a5503397c705a2b27ab33dfbaf5930738
