### ISSUE TITLE
suppoer jalalli date

### ISSUE THREAD

**Issue by mohamad171** [FreddyFY/material-datepicker#16]
Hi , how can i show date as persian?
i use momentjs and it's work for result , but in showing dates in calender it's show georgian date!!!
How can i fix this?

**Comment by FreddyFY** [comment]
Hi @mohamad171, do you have a Minimal working example? Than i can test it out.

**Comment by mohamad171** [comment]
Hi @FreddyFY 

Example: 

[JSFiddle](https://jsfiddle.net/zaed4m3g/5/)

[Gist](https://gist.github.com/mohamad171/899064f5c3623cb9666ea7c46a7671c0)

 date that showing in input is correct but the days showing in datepicker window is not correct and it's show georgian...

i want to change datepicker to show jalalli,
thanks.

**Comment by FreddyFY** [comment]
@mohamad171 
In [🔖 1.0.7](https://github.com/FreddyFY/material-datepicker/releases/tag/1.0.7) there is a minimal support for jalalli dates.
Check it out here: https://jsfiddle.net/twxdue9b/1/

The first of month is not at the beginning, but clicking on a date, works.
I will not make more changes to optimize it, because I don't know enought about persian dates.

PR are always welcome!
